### ISSUE TITLE
Maybe DevUtils can not work on the right way on M1

### ISSUE THREAD

**Issue by LocNguyenHuu** [DevUtilsApp/DevUtils-app#100]
Need your supporting to help me fix this error when I try to build DevUtils on my Macbook 14" M1.
Google, stackoverflow gave many solutions but still not working.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/9362970/182750169-c8d3ea96-8c9e-4a60-a633-b6ecf24c0b79.png">

**Comment by trungdq88** [comment]
Hi @LocNguyenHuu, I'm unable to provide support regarding build issues. Sorry!
