### ISSUE TITLE
error build: Undefined symbol

### ISSUE THREAD

**Issue by h4rk8s** [DevUtilsApp/DevUtils-app#103]
`error build: Undefined symbol: _OBJC_CLASS_$_Diff

error build: Undefined symbol: _OBJC_CLASS_$_DiffMatchPatch

error build: Undefined symbol: _OBJC_CLASS_$_SRRecorderControl

error build: Undefined symbol: _OBJC_CLASS_$_SRShortcut

error build: Undefined symbol: _OBJC_CLASS_$_SRShortcutValidator

error build: Undefined symbol: _OBJC_CLASS_$_SUUpdater

error build: Undefined symbol: _OBJC_METACLASS_$_SUUpdater
`

macOS 12.6
Xcode 14.0
M1 Mac

**Comment by badwulfy** [comment]
How did you solve the issue ?

**Comment by damoncoo** [comment]
Same issue here, any solution ?

**Comment by vkaelin** [comment]
Same error

**Comment by usanjar** [comment]
same error, @h4rk8s any solution?

Undefined symbol: _OBJC_CLASS_$_Diff
Undefined symbol: _OBJC_CLASS_$_DiffMatchPatch
Undefined symbol: _OBJC_CLASS_$_SUUpdater
Undefined symbol: _OBJC_METACLASS_$_SUUpdater
Linker command failed with exit code 1 (use -v to see invocation)
