### ISSUE TITLE
Feature request: DiffChecker

### ISSUE THREAD

**Issue by audip** [DevUtilsApp/DevUtils-app#11]
Numerous people use online diff checkers to compare files, PDFs, code snippets and a way to compare them offline is going to make this app super awesome.

**Comment by trungdq88** [comment]
Hi there,

Thanks for the suggestion, I'll look into this. Hopefully can be added in the next few updates :)

**Comment by trungdq88** [comment]
Text Diff Checker is added to the app :)

![diff](https://user-images.githubusercontent.com/4214509/95644742-d48f9b80-0ae2-11eb-9676-0a225adbd5e5.gif)

**Comment by audip** [comment]
Dope, will check it out. The turnaround time is impressive.

**Comment by CostcoFanboy** [comment]
Any chance for a JSON diff?
