### ISSUE TITLE
Build instructions aren't comprehensive enough for those of us who aren't MacOS/iOS devs

### ISSUE THREAD

**Issue by adamhopkinson** [DevUtilsApp/DevUtils-app#13]
This looks like a great app - however, coming from a web app background the build instructions are not comprehensive enough.

1. **Clone repository**. Easy enough, git is fairly universal for all devs
2. **Bootstrap carthage: carthage bootstrap --platform macOS**. Installed carthage using brew, ran the command
3. **Update signing Team to be your Personal or organizational Team**. What?
4. **Run**. Run what? Admittedly I've not done step 3, but I would expect step 2 would result in an app file somewhere.

I do appreciate the effort that's gone into making this and understand that for a small fee I could buy the app built - but you'd have a much larger audience if you made the open source instructions more inclusive for non-Apple devs.

**Comment by trungdq88** [comment]
Hi, sorry for the ambiguous, I'll try to improve the doc on the weekend.

I found a good document explaining how to Update the signing Team in XCode, maybe it will help:
- https://developer.apple.com/support/code-signing/
- https://help.apple.com/xcode/mac/current/#/dev60b6fbbc7 (click through the submenu in the sidebar, there are pictures)

As for "Run", it means you click the "Run" button in Xcode to build and run the app.

**Comment by trungdq88** [comment]
Hope you have successfully built the app. Feel free to reopen if you have more questions.

Also, I'll really appreciate it if you could share the problems/workarounds during your build process, as it may help others to build the project.

Thanks!
