### ISSUE TITLE
Add support for XML formatter/validator

### ISSUE THREAD

**Issue by soleo** [DevUtilsApp/DevUtils-app#14]
For some projects I have worked on in the past, XML is used as the data format. E.g sitemaps, product catalog exports, etc. Would like to see a feature to prettify large XML files

**Comment by trungdq88** [comment]
Hi, thanks for the suggestion. This will be put in the backlog for future versions. Stay tuned for the updates. Cheers!

**Comment by trungdq88** [comment]
You can now format XML as of version 1.4.0 😊
Validation coming soon!

![image](https://user-images.githubusercontent.com/4214509/96337602-8cf4ab00-10b2-11eb-9e8e-367c5c55f370.png)
