### ISSUE TITLE
Support simple math expression in unix time converter input

### ISSUE THREAD

**Issue by sudo-suhas** [DevUtilsApp/DevUtils-app#15]
Could you please add support for simple math expression such as `1601954752+49634` as the input for unix time converter? Right now, it fails with 'Invalid input'.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/22251956/95155468-d63f2380-07b1-11eb-8351-6443ec592cc5.png">

**Comment by trungdq88** [comment]
Hm, at the first glance I don't see this is needed. Can you explain more on what is your workflow that leads to the need for this feature?

**Comment by sudo-suhas** [comment]
I was trying to figure out the timestamp of expiry using the TTL for a key in redis. Since that value is seconds to expiry, adding that to current time gives me the answer.

**Comment by trungdq88** [comment]
Oh I see. This actually makes sense, thanks for sharing.
I'll try to support +-*/ operators in the next versions.

**Comment by trungdq88** [comment]
You can now use math operators in the Unix Timestamp Converter tool 😊
![image](https://user-images.githubusercontent.com/4214509/96337563-5ae34900-10b2-11eb-9a17-8d25c7ba386a.png)

**Comment by sudo-suhas** [comment]
Thank you! Very happy that I purchased this app, love it and use it every day 🎉
