### ISSUE TITLE
Reciepe

### ISSUE THREAD

**Issue by FNGR2911** [DevUtilsApp/DevUtils-app#16]
Thanks yor the app! I bought it a few minutes ago and really really like it! But other than promised on the thank you page, I just got a download link – no reciepe. How do I get one? Really need it.

**Comment by trungdq88** [comment]
Hi there, thank you for buying the app!

The receipt is sent in a separate email by Stripe, please also look into the Spam folder.
If you still can't find it, please send me an email to admin@devutils.app using the email you used to purchase. I'll look up your receipt and resend it to you.

Cheers!

**Comment by FNGR2911** [comment]
Thank you, the reciepe landed in spam :)
