### ISSUE TITLE
Feature Request: Regex

### ISSUE THREAD

**Issue by tsmith-rv** [DevUtilsApp/DevUtils-app#17]
I think something that would fit in perfectly with these tools is a simple regex match tester. Something like what you would find on https://regex101.com/, but without the explanation box or anything too complex, at least to start. 

Just the two inputs for your pattern and your string to test against, along with a list of matches in the right side bar. Maybe even syntax highlighting the matches? I think that would be a great addition.

**Comment by trungdq88** [comment]
Hi there,

Thank you for the suggestion! Regex tester is on the way, it won't be a full-blown regex analyzer like regex101.com but it will be enough for basic usages as you described.

Stay tuned for the new versions :)

**Comment by trungdq88** [comment]
@tsmith-rv Just want to let you know, you can now use DevUtils with Regex :) 

![image](https://user-images.githubusercontent.com/4214509/102001624-cb12f180-3d26-11eb-9dbf-b0cc39c9e7fa.png)

You can follow the app's update on Twitter to receive more recent updates: https://twitter.com/devutils_app

Thanks!

**Comment by Nezteb** [comment]
Why did this get re-opened? The RegExp Tester works wonderfully! 😄
