### ISSUE TITLE
No such module 'ShortcutRecorder'

### ISSUE THREAD

**Issue by Avalfr3d** [DevUtilsApp/DevUtils-app#19]
Hi People,

with Xcode (Version 11.7 (11E801a)) fail build with this error:
**No such module 'ShortcutRecorder'**

<img width="715" alt="Screenshot 2020-10-08 at 3 30 18 PM" src="https://user-images.githubusercontent.com/68288974/95465265-31704200-097b-11eb-97bc-58a0b2f593d2.png">

**Comment by trungdq88** [comment]
Hi there,

Make sure you have run `carthage bootstrap --platform macOS` as noted in the build instruction.

**Comment by Avalfr3d** [comment]
Hi @trungdq88 

thanks!
Carthage was the problem (not installed).

Al
