### ISSUE TITLE
Mac App Store?

### ISSUE THREAD

**Issue by chriskacerguis** [DevUtilsApp/DevUtils-app#2]
Would it be possible to submit this to the Mac App store?  I'd be happy to pay more for it to offset the costs.  It's easier to manage all my licenses via App store (vs emails/license keys/etc).

**Comment by xC0der** [comment]
Same here!

**Comment by trungdq88** [comment]
Should not be a problem, I'll try to see if I can make it available this week. Thanks for your support!

**Comment by chriskacerguis** [comment]
@trungdq88 thanks!!  I’m happy to buy it again to help a fellow dev.

**Comment by trungdq88** [comment]
@chriskacerguis @xC0der The app is up :) https://apps.apple.com/us/app/id1533756032

If you purchase on App Store and want a refund on the standalone build, please send me your App Store receipt, I'm happy to refund you on Stripe.

I also just created a Twitter account: https://twitter.com/devutils_app I'll post more regular updates on it.

Thanks!

**Comment by chriskacerguis** [comment]
This is awesome @trungdq88 I just purchased it!
