### ISSUE TITLE
Signing error

### ISSUE THREAD

**Issue by johncaling40** [DevUtilsApp/DevUtils-app#20]
I get error
```
No account for team "432TM87K7L". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
```
and
```
No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "432TM87K7L" with a private key was found.
```

I have changed the Team in the Signing and Capabilities tab of the DevUtils project to my personal team. How do I fix this?

**Comment by trungdq88** [comment]
Hi there,
Can you try to set the signing to "Sign to run locally"? This article may also help https://developer.apple.com/support/code-signing/

**Comment by johncaling40** [comment]
I got it to work thanks. I had to change the thing in other places.
