### ISSUE TITLE
Feature Request: Lorem ipsum text generator

### ISSUE THREAD

**Issue by davidcann** [DevUtilsApp/DevUtils-app#21]
Something like generator.lorem-ipsum.info to generate placeholder text would be useful.

Maybe add options to specifically include non-ASCII characters and emoji, which would be useful in testing software to ensure that string handling is correct.

**Comment by trungdq88** [comment]
Hi David,

Lorem ipsum is in the backlog and will be added soon. The non-ASCII characters and emoji generator is also interesting. I'll look into it :) Thanks for the suggestions!

**Comment by revolter** [comment]
Isn't this fixed?

**Comment by trungdq88** [comment]
Yep it is. @davidcann Now you can generate stuff from version 1.7.0:

![image](https://user-images.githubusercontent.com/4214509/103658855-5c7c2900-4f9e-11eb-9d63-7b43da9db6ed.png)

Cheers!

**Comment by trungdq88** [comment]
Special characters, emoijs, and a few other string related feature is planned in another tool "String generator". Stay tuned 😄

**Comment by davidcann** [comment]
Great work!
