### ISSUE TITLE
[Feat] QR Code Generator

### ISSUE THREAD

**Issue by gozeon** [DevUtilsApp/DevUtils-app#25]
such as [link](https://www.the-qrcode-generator.com/)

**Comment by DavidPhillipOster** [comment]
https://old.reddit.com/r/swift/comments/ce5lvy/does_anybody_know_a_good_api_for_generating_qr/etzzy9q/?context=3 is an example of how easy this would be to do, since the CoreImage framework is doing all the hard work.

**Comment by trungdq88** [comment]
@gozeon  @DavidPhillipOster If you are using the direct download version, opt-in for 1.8.0 beta to try out the new QR Code Generator 😄 

![CleanShot 2021-02-05 at 19 54 19@2x](https://user-images.githubusercontent.com/4214509/107036273-f1678180-67eb-11eb-8cd3-8b2ca128aa26.png)

**Comment by trungdq88** [comment]
1.8.0 is out! 😄
