### ISSUE TITLE
Cheaper version :D

### ISSUE THREAD

**Issue by devutils2** [DevUtilsApp/DevUtils-app#32]
i have released cheaper version :D of devutils its 5 dolar only come on get it! https://devutils2.app/

**Comment by trungdq88** [comment]
Hi there,

Please note that the source code is only available for auditing and personal use. Which means you don't have permission to redistribute the app.

You can view the license of this software here: https://github.com/DevUtilsApp/DevUtils-app/blob/master/LICENSE.md

Please remove the download link on your website.

Thank you.
