### ISSUE TITLE
[Feature] Regex pattern test for multiline

### ISSUE THREAD

**Issue by tunguyen9889** [DevUtilsApp/DevUtils-app#37]
Hi there,

Thanks for awesome tool, I just bought it! It would be great if the Regex tester can work for multiline. Attached the screenshoot about my usecase.

![Screen Shot 2020-12-17 at 6 49 19 PM](https://user-images.githubusercontent.com/18132847/102484286-9d1c0d00-4098-11eb-90ad-1c3f4db5a5fc.jpg)

Thanks,
James

**Comment by trungdq88** [comment]
Hello James,

Thank you very much for your purchase!

The tool is using the [ICU regex engine](https://developer.apple.com/documentation/foundation/nsregularexpression), so if you want to match multiline, the `?m` flag need to be enabled. You can do that by clicking the small gear icon and tick the option as below:

![image](https://user-images.githubusercontent.com/4214509/102492400-36045580-40a4-11eb-924d-3e2cb6a00cee.png)

Can you try this and let me know if it would return your desired result? Here is what it shows from my side:

![image](https://user-images.githubusercontent.com/4214509/102492477-53392400-40a4-11eb-9619-72efc3e8293b.png)

**Comment by tunguyen9889** [comment]
Thanks for your quick reply! It works as expected!
