### ISSUE TITLE
Crash app on Number Base Converter

### ISSUE THREAD

**Issue by dinhquochan** [DevUtilsApp/DevUtils-app#39]
### Description

Crash app on Number Base Converter feature

### Steps to reproduce

1. Open DevUtils
2. Choose **Number Base Converter**
3. On fields: Base 2, 8, 10, 16 -> Type <number>
4. Crash app

![image](https://user-images.githubusercontent.com/9979458/102565672-81ece400-4110-11eb-97f1-09b27cfbea82.png)

### Environment

* Version: 1.6.0
* OS: macOS 11.1

**Comment by trungdq88** [comment]
Hi @dinhquochan, thank you very much for reporting the issue. Can you help send the crash log via my email so I can inspect it further? tony@devutils.app

Looks like it only happens on Big Sur, do more testing on this. Thanks!

**Comment by trungdq88** [comment]
This should be fixed now in version 1.6.1. Thank you very much for reporting! Feel free to reopen if you still have this problem.

Thanks.
