### ISSUE TITLE
[Feature] Convert JSON into gorgeous, typesafe code in any language.

### ISSUE THREAD

**Issue by quocthinh212** [DevUtilsApp/DevUtils-app#41]
Convert JSON into gorgeous, typesafe code in any language.
Like https://github.com/quicktype/quicktype
and http://www.jsoncafe.com/

**Comment by trungdq88** [comment]
Hi there,

Thank you for your suggestion. There is already an issue created for this (https://github.com/DevUtilsApp/DevUtils-app/issues/7), so I'll close this one as it is duplicated.

Thanks.
