### ISSUE TITLE
[Feature] Remember tool settings between app restarts

### ISSUE THREAD

**Issue by lemonmojo** [DevUtilsApp/DevUtils-app#45]
Some tools offer settings that are currently not persisted and reset to their default values after restarting the app.
For instance, all the beautify/minify tools offer a setting to control the number of spaces or tabs. But that setting resets to its default value after restarting the app.

**Comment by revolter** [comment]
Isn't this fixed?

**Comment by lemonmojo** [comment]
@trungdq88 Awesome! Already tested and working fine so far. Thx!

**Comment by trungdq88** [comment]
So the symlink sync works? That's great! 😄

**Comment by lemonmojo** [comment]
@trungdq88 Oh sorry, wasn't clear about that, I just tested the persistence of the tool settings, not syncing.

**Comment by trungdq88** [comment]
Oh okay, it's fine. I'll give it a test later.

**Comment by revolter** [comment]
> The user preferences file location is also available in the Preferences panel.

I can't find it:

![image](https://user-images.githubusercontent.com/5748627/103662730-f7620c80-4f78-11eb-8cf6-38cc2c05f5ee.png)

**Comment by trungdq88** [comment]
@revolter It's in 1.7.1. If you are using DevUtils from App Store or Setapp, it will take a few more days for their approval 😅  Sorry about that.

**Comment by trungdq88** [comment]
![image](https://user-images.githubusercontent.com/4214509/103662974-27260a00-4fa3-11eb-9927-2e1c59870420.png)

Looks like this btw
