### ISSUE TITLE
Add favourite tools support

### ISSUE THREAD

**Issue by revolter** [DevUtilsApp/DevUtils-app#50]
It would be nice if you could have a separate list of favourite tools, so they're easier to access, especially when searching a couple of letters gives you more than 1 result, and you have to scan all of them to figure out which one you actually need.

**Comment by trungdq88** [comment]
Hi there!

Absolutely, this will be soon available.

Thanks for the suggestion 😄

**Comment by trungdq88** [comment]
@revolter you can now manage your favorite tools. Opt-in for 1.8.0 beta to give it a try 😄 
![CleanShot 2021-02-05 at 20 00 22@2x](https://user-images.githubusercontent.com/4214509/107036820-ca5d7f80-67ec-11eb-826a-7b1df9eb9ecc.png)

**Comment by revolter** [comment]
Hmm, does this mean that deselecting a tool from that "Manage Tools" window causes it to completely disappear from the main window?

**Comment by trungdq88** [comment]
Hi, yes, that's what the Manage Tools do 😄

I'm looking to add more features to categorize tools or create custom tool lists soon.

PS: for now, you can also reorder the tools list to move your favorite tools to the top.

**Comment by trungdq88** [comment]
1.8.0 is out! https://devutils.app/changelog

@revolter I'm keeping a private note for "tool categorizing and custom tool list". However, if you prefer to be notified when it's out, feel free to create another issue, I'll update it as it goes. Thanks 😄

**Comment by revolter** [comment]
> 1.8.0 is out!

Congrats! 🎉

> @revolter I'm keeping a private note for "tool categorizing and custom tool list". However, if you prefer to be notified when it's out, feel free to create another issue, I'll update it as it goes. Thanks 😄

Ok 👍🏻
