### ISSUE TITLE
Add tools keywords for search

### ISSUE THREAD

**Issue by revolter** [DevUtilsApp/DevUtils-app#51]
For example, it would be nice if, when searching for "binary" or "decimal", the "Number Base Converter" tool would show up.

**Comment by trungdq88** [comment]
Hi there! This is a very good suggestion. Thank you, added to to-do list 😄

**Comment by trungdq88** [comment]
@revolter If you are using the direct download version, opt-in for 1.8.0 beta to try out the new search 😄 

GIF: https://twitter.com/i/status/1357600821920157700

**Comment by revolter** [comment]
I installed it from the App Store, so I'll wait for the official release 😃

**Comment by trungdq88** [comment]
1.8.0 is out, closing this now 😄 

@revolter the App Store update may come in a bit late, I can't control it as the App Store reviewer needs some "additional time". Sorry in advance.
