### ISSUE TITLE
Add QR code encoder/decoder

### ISSUE THREAD

**Issue by revolter** [DevUtilsApp/DevUtils-app#52]
Maybe by pasting/dragging an image, or pasting a link to an image.

**Comment by trungdq88** [comment]
Thanks for the suggestion! There is already a request for this (https://github.com/DevUtilsApp/DevUtils-app/issues/25) so I'll close this one. Let me know if you have any concerns.

**Comment by revolter** [comment]
Sorry 🙈 I must have forgotten to search an existing issue before creating this.
