### ISSUE TITLE
[Feature] Close app when clicking menu bar app icon

### ISSUE THREAD

**Issue by jlarmstrongiv** [DevUtilsApp/DevUtils-app#60]
Many apps that live in the menu bar can be clicked to open.  But, they can also be clicked to close (if they’ve been opened).  Would be a nice usability touch to add 😄

(So, when the app is open, clicking the menu bar icon would close all open windows)

Examples:
- https://www.glyphfinder.com/
- https://usecontrast.com/
- https://rogueamoeba.com/soundsource/

**Comment by trungdq88** [comment]
Hello John, thanks for the suggestion. This is actually very helpful. Noted. 😄

**Comment by trungdq88** [comment]
@jlarmstrongiv This is now implemented in 1.9.0! 😊 https://twitter.com/devutils_app/status/1388874971976409092
