### ISSUE TITLE
Not "Open Source"

### ISSUE THREAD

**Issue by EtherTyper** [DevUtilsApp/DevUtils-app#65]
I'm not a stickler myself, but you probably should not label your software as open source. The new license restricts selling and publishing modifications to software, so "source available" is a more accurate term.

https://en.wikipedia.org/wiki/Open-source_software
https://opensource.org/osd

Edit: Love your app by the way, thanks for all the work you do on it! I use it frequently.

**Comment by trungdq88** [comment]
Hi there! You are absolutely right. I didn't notice that the term "open source" now (strictly?) refers to the [Open Source Definition](https://opensource.org/osd).

I'll update README and website description to avoid any potential unnecessary debates 😄 .

 Thanks!

**Comment by trungdq88** [comment]
Updated
