### ISSUE TITLE
JSON to Struct Codable converter

### ISSUE THREAD

**Issue by Narrorek** [DevUtilsApp/DevUtils-app#7]
Hello,

It Will be great if you add json to struct codable converter like https://quicktype.io/.

Thanks.

**Comment by trungdq88** [comment]
Nice. Since Quicktype is open source, it may help with the integration a lot. I'll look into this, thanks!

**Comment by Narrorek** [comment]
i will keep fingers crossed - good luck!

Please remove XIBs, try to create UI in swift :P

**Comment by PeterBurner** [comment]
the other way round would also be pretty useful
I often need to convert JavaScript Objects into JSON
unfortunately Quicktype can't do that 😞
