### ISSUE TITLE
Missing space in minified @media only screen and (...){...}

### ISSUE THREAD

**Issue by bardonadam** [DevUtilsApp/DevUtils-app#70]
I was minifying CSS with `@media only screen and (...){...}` and the minified version wasn't working for me properly. Took me some time to figure out why, but DevUtils minified output for:
`@media only screen and (...){...}`
is 
`@media only screen and(...){...}`

There is a missing space between `and` and `(`.

**Comment by trungdq88** [comment]
Hi there, thanks for reporting this. I'll take a look and fix it in the next version 😄

**Comment by trungdq88** [comment]
@bardonadam This is now fixed in 1.9.0 😄 Can you help check if it works now?

https://twitter.com/devutils_app/status/1388874971976409092

Feel free to reopen if the problem is still theree.
