### ISSUE TITLE
RegExp Tester should highlight capture group text separately in the preview

### ISSUE THREAD

**Issue by aescolastico** [DevUtilsApp/DevUtils-app#71]
It is a common to use a reg exp to match a string and then use capture groups to highlight or "capture" specific portions of that matched string. Regex101.com does this. See example below:

![image](https://user-images.githubusercontent.com/30540257/114662541-da9b4a80-9cc6-11eb-9fd9-1f0ce1232120.png)

**Comment by trungdq88** [comment]
Hi there, thanks for the suggestion! This is something I want to add to the regex tool as well, stay tuned :)

**Comment by trungdq88** [comment]
There is no highlight yet, but the Regex Tester tool is now (version 1.12) upgraded to support matching groups and named capture groups!

![CleanShot 2021-10-08 at 22 36 02@2x](https://user-images.githubusercontent.com/4214509/136575782-80e06d73-c3b7-49e2-8c92-40daf31ba27c.png)

I'll keep a separate ticket to track the next upgrade: regex syntax highlight and show more details when mouse hover to groups.

Closing this for now, let me know if you have any other questions! 😊
