### ISSUE TITLE
Support multiple JSON lines in JSON Linter.

### ISSUE THREAD

**Issue by danielewood** [DevUtilsApp/DevUtils-app#8]
Quite often I'll be dealing with JSON formatted logs with lines of JSON. It would be nice if I could paste a section in and it lint all the input.

![image](https://user-images.githubusercontent.com/23008560/94891014-c3d18c80-0435-11eb-96cc-e9cc1fc6bf67.png)

As a bonus, instead of showing "Invalid JSON", if it could have an option to partially-parse the JSON and highlight the syntax errors, much like VS Code does, that would be lovely.
VS Code Example(removed an end quote from price):

![image](https://user-images.githubusercontent.com/23008560/94891182-3c384d80-0436-11eb-8b82-9005f9dc3e78.png)

**Comment by trungdq88** [comment]
Thanks, Daniel. These are all good suggestions. The multi-lines JSON may mess-up with the "showing selected JQ path" a bit but I believe there as ways to work around that.

I'll put these all into my backlog, thanks!

**Comment by trungdq88** [comment]
This is now supported as of version 1.3.0: 
- Syntax error highlighting
- Support multi-lines JSON (from logs or JSON stream)
- Partially format the string where possible

This is it for now, there will be more improvements to the JSON tool in the future 😄 

![image](https://user-images.githubusercontent.com/4214509/95652999-71702a00-0b1f-11eb-8743-3f99e5a3978b.png)
