### ISSUE TITLE
Can the feature of password generator be added?

### ISSUE THREAD

**Issue by zhongyiio** [DevUtilsApp/DevUtils-app#84]
Same as title.

**Comment by trungdq88** [comment]
Now available in version 1.14! 🥳

![CleanShot 2022-04-11 at 20 13 58@2x](https://user-images.githubusercontent.com/4214509/162747140-e524dc7f-a2ab-4447-accc-3e7f5f019149.png)

<img width="434" alt="CleanShot 2022-04-11 at 20 14 15@2x" src="https://user-images.githubusercontent.com/4214509/162747185-1c302568-b198-440e-a71f-6940c0f7a227.png">

**Comment by zhongyiio** [comment]
Thanks for the feature.
