### ISSUE TITLE
Set substitution defaults

### ISSUE THREAD

**Issue by danielewood** [DevUtilsApp/DevUtils-app#9]
Initially I was having issues with JSONs due to my system wide substitution being the macOS default of smart-quotes. As soon as I would click the JSON example, it would appear momentarily, then show as `Invalid JSON`.

I think it would be beneficial for DevUtils to be opinionated and default to either disabling smart quote substitution or set the substitution to be classic straight quotes. This may be an Apple thing you cant change.

Example of what the defaults should probably be:
![image](https://user-images.githubusercontent.com/23008560/94891499-19f2ff80-0437-11eb-86a6-3858cc5eb6c0.png)

**Comment by trungdq88** [comment]
Thanks! I have also received a few reports about smart quotes. For now, I'll make the JSON tool consider "smart" and "dump" quotes the same, this should resolve the issue for most cases. Stay tuned for the next update :)

For custom text replacement and other substitutions, I'll see if I can add it in in the future.

**Comment by trungdq88** [comment]
Hi Daniel, this is fixed from version 1.3.0. All the input texts in the app will not automatically substitute smart quotes and dashes. The JSON tool also automatically replace any smart quotes it found (you can disable this using the gear button in the tool).

![image](https://user-images.githubusercontent.com/4214509/95652971-2c4bf800-0b1f-11eb-95fd-49e036a27b11.png)

Thanks!
