### ISSUE TITLE
Highlightr error

### ISSUE THREAD

**Issue by yaoyi2008** [DevUtilsApp/DevUtils-app#95]
$ carthage bootstrap --platform macOS
*** Checking out ShortcutRecorder at "3.3.0"
*** Checking out Highlightr at "2.1.1"
*** xcodebuild output can be found in /var/folders/b6/3p4psc6x6fnbv84226snn34c0000gn/T/carthage-xcodebuild.BD8bfM.log
*** Downloading ShortcutRecorder binary at "3.3.0 (2020-07-12)"
*** Skipped building Highlightr due to the error:
Dependency "Highlightr" has no shared framework schemes for any of the platforms: Mac

macOS 13.0 Beta版(22A5266r)
xcode-select version 2395

**Comment by trungdq88** [comment]
Hi @yaoyi2008, due to limited time, I will not be able to help with build issue. Sorry.
